export const BASE_SKILLS = [
    {name: "accounting", label: "Accounting", base: 5},
    {name: "anthropology", label: "Anthropology", base: 1},
    {name: "appraise", label: "Appraise", base: 5},
    {name: "archaeology", label: "Archaeology", base: 5},
    {name: "charm", label: "Charm", base: 15},
    {name: "climb", label: "Climb", base: 20},
    {name: "credit_rating", label: "Credit Rating", base: 0},
    {name: "cthulhu_mythos", label: "Cthulhu Mythos", base: 0},
    {name: "disguise", label: "Disguise", base: 5},
    {name: "dodge", label: "Dodge", base: -1},
    {name: "drive_auto", label: "Drive Auto", base: 20},
    {name: "electrical_repair", label: "Electrical Repair", base: 10},
    {name: "fast_talk", label: "Fast Talk", base: 5},
    {name: "fighting_brawl", label: "Fighting (Brawl)", base: 25},
    {name: "firearms_handgun", label: "Firearms (Handgun)", base: 20},
    {name: "firearms_rifle_shotgun", label: "Firearms (Rifle/Shotgun)", base: 25},
    {name: "first_aid", label: "First Aid", base: 30},
    {name: "history", label: "History", base: 5},
    {name: "intimidate", label: "Intimidate", base: 15},
    {name: "jump", label: "Jump", base: 20},
    {name: "language_own", label: "Language (Own)", base: -1},
    {name: "law", label: "Law", base: 5},
    {name: "library_use", label: "Library Use", base: 20},
    {name: "listen", label: "Listen", base: 20},
    {name: "locksmith", label: "Locksmith", base: 1},
    {name: "mechanical_repair", label: "Mechanical Repair", base: 10},
    {name: "medicine", label: "Medicine", base: 1},
    {name: "natural_world", label: "Natural World", base: 10},
    {name: "navigate", label: "Navigate", base: 10},
    {name: "occult", label: "Occult", base: 5},
    {name: "operate_hv_machinery", label: "Operate Heavy Machinery", base: 1},
    {name: "persuade", label: "Persuade", base: 10},
    {name: "psychology", label: "Psychology", base: 10},
    {name: "psychoanalysis", label: "Psychoanalysis", base: 1},
    {name: "ride", label: "Ride", base: 5},
    {name: "science", label: "Science", base: 1},
    {name: "sleight_of_hand", label: "Sleight of Hand", base: 10},
    {name: "spot_hidden", label: "Spot Hidden", base: 25},
    {name: "stealth", label: "Stealth", base: 20},
    {name: "survival", label: "Survival", base: 10},
    {name: "swim", label: "Swim", base: 20},
    {name: "throw", label: "Throw", base: 20},
    {name: "track", label: "Track", base: 10}
]

export const WEAPON_SKILLS = [
    {name: "fighting_brawl", label: "Fighting (Brawl)", base: 25},
    {name: "firearms_handgun", label: "Firearms (Handgun)", base: 20},
    {name: "firearms_rifle_shotgun)", label: "Firearms (Rifle/Shotgun)", base: 25}
]