export const SKILLS = [
    {label: "Boat", group: "dexterity"},
    {label: "Climb", group: "dexterity"},
    {label: "Dodge", group: "dexterity"},
    {label: "Drive", group: "dexterity"},
    {label: "Fly", group: "dexterity"},
    {label: "IceSkate", group: "dexterity"},
    {label: "Jump", group: "dexterity"},
    {label: "Ride (Boar)", group: "dexterity"},
    {label: "Ride (Griffin)", group: "dexterity"},
    {label: "Ride (Horse)", group: "dexterity"},
    {label: "Ride (Praxian Beast)", group: "dexterity"},
    {label: "Ride (Triceratops)", group: "dexterity"},
    {label: "Ride", group: "dexterity"},
    {label: "Ski", group: "dexterity"},
    {label: "Swim", group: "dexterity"},
    {label: "Act", group: "communication"},
    {label: "Art", group: "communication"},
    {label: "Bargain", group: "communication"},
    {label: "Charm", group: "communication"},
    {label: "Courtesan", group: "communication"},
    {label: "Dance", group: "communication"},
    {label: "Disguise", group: "communication"},
    {label: "Fast talk", group: "communication"},
    {label: "Intimidate", group: "communication"},
    {label: "Intrigue", group: "communication"},
    {label: "Orate", group: "communication"},
    {label: "Sing", group: "communication"},
    {label: "Speak (Other)", group: "communication"},
    {label: "Speak Auld Wyrmish", group: "communication"},
    {label: "Speak Balazaring", group: "communication"},
    {label: "Speak Beast Speech", group: "communication"},
    {label: "Speak Brithini", group: "communication"},
    {label: "Speak Caladralander", group: "communication"},
    {label: "Speak Carmanian", group: "communication"},
    {label: "Speak Dara Happan", group: "communication"},
    {label: "Speak Dark Tongue", group: "communication"},
    {label: "Speak Earth Tongue", group: "communication"},
    {label: "Speak Esrolian", group: "communication"},
    {label: "Speak Firespeech", group: "communication"},
    {label: "Speak Heortling", group: "communication"},
    {label: "Speak Kareeshtan", group: "communication"},
    {label: "Speak Kralori", group: "communication"},
    {label: "Speak Malki", group: "communication"},
    {label: "Speak Mostali", group: "communication"},
    {label: "Speak New Pelorian", group: "communication"},
    {label: "Speak Old Pavic", group: "communication"},
    {label: "Speak Other Language (Aldryami)", group: "communication"},
    {label: "Speak Other Language (Dark Tongue)", group: "communication"},
    {label: "Speak Other Language (Tarshite)", group: "communication"},
    {label: "Speak Pelaskan", group: "communication"},
    {label: "Speak Pure Horse Tongue", group: "communication"},
    {label: "Speak River Speech", group: "communication"},
    {label: "Speak Safelstran", group: "communication"},
    {label: "Speak Seaspeech", group: "communication"},
    {label: "Speak Seshnegi", group: "communication"},
    {label: "Speak Slargetongue", group: "communication"},
    {label: "Speak Spirit Speech", group: "communication"},
    {label: "Speak Stormspeech", group: "communication"},
    {label: "Speak Tanyen", group: "communication"},
    {label: "Speak Tarshite", group: "communication"},
    {label: "Speak Telmori", group: "communication"},
    {label: "Speak Thellan", group: "communication"},
    {label: "Speak Thieves Argot", group: "communication"},
    {label: "Speak Tradetalk", group: "communication"},
    {label: "Speak Vorumai", group: "communication"},
    {label: "Alchemy", group: "knowledge"},
    {label: "Aldryami Lore", group: "knowledge"},
    {label: "Animal lore", group: "knowledge"},
    {label: "Battle", group: "knowledge"},
    {label: "Beast Folk Lore", group: "knowledge"},
    {label: "Bureaucracy", group: "knowledge"},
    {label: "Celestial Lore", group: "knowledge"},
    {label: "Cult Lore (Chalana Arroy)", group: "knowledge"},
    {label: "Cult Lore (Engizi)", group: "knowledge"},
    {label: "Cult Lore (Ernalda)", group: "knowledge"},
    {label: "Cult Lore (Eurmal)", group: "knowledge"},
    {label: "Cult Lore (Humakt)", group: "knowledge"},
    {label: "Cult Lore (Issaries)", group: "knowledge"},
    {label: "Cult Lore (Kolat)", group: "knowledge"},
    {label: "Cult Lore (Lanbril)", group: "knowledge"},
    {label: "Cult Lore (Lhankor Mhy)", group: "knowledge"},
    {label: "Cult Lore (Lokarnos)", group: "knowledge"},
    {label: "Cult Lore (Maran Gor)", group: "knowledge"},
    {label: "Cult Lore (Odayla)", group: "knowledge"},
    {label: "Cult Lore (Orlanth)", group: "knowledge"},
    {label: "Cult Lore (Other)", group: "knowledge"},
    {label: "Cult Lore (Seven Mothers)", group: "knowledge"},
    {label: "Cult Lore (Storm Bull)", group: "knowledge"},
    {label: "Cult Lore (Telmor)", group: "knowledge"},
    {label: "Cult Lore (Yelm)", group: "knowledge"},
    {label: "Cult Lore (Yelmalio)", group: "knowledge"},
    {label: "Cult Lore (Ygg)", group: "knowledge"},
    {label: "Cult Lore (Yinkin)", group: "knowledge"},
    {label: "Cult Lore (Zola Fel)", group: "knowledge"},
    {label: "Customs (Beast Folk)", group: "knowledge"},
    {label: "Customs (East Isles)", group: "knowledge"},
    {label: "Customs (Esrolian)", group: "knowledge"},
    {label: "Customs (Ludoch)", group: "knowledge"},
    {label: "Customs (Other)", group: "knowledge"},
    {label: "Customs (Own)", group: "knowledge"},
    {label: "Customs (River Folk)", group: "knowledge"},
    {label: "Customs (Trolls)", group: "knowledge"},
    {label: "Customs Durulz", group: "knowledge"},
    {label: "Customs Lunar Heartlands", group: "knowledge"},
    {label: "Customs Newtling", group: "knowledge"},
    {label: "Customs Telmori", group: "knowledge"},
    {label: "Draconic Lore", group: "knowledge"},
    {label: "Durulz Lore", group: "knowledge"},
    {label: "Elder Races Lore", group: "knowledge"},
    {label: "Evaluate", group: "knowledge"},
    {label: "Farm", group: "knowledge"},
    {label: "First Aid", group: "knowledge"},
    {label: "Game", group: "knowledge"},
    {label: "Herd", group: "knowledge"},
    {label: "Homeland Lore (Esrolia)", group: "knowledge"},
    {label: "Homeland Lore (Fereva)", group: "knowledge"},
    {label: "Homeland Lore (Fonrit)", group: "knowledge"},
    {label: "Homeland Lore (Heortland)", group: "knowledge"},
    {label: "Homeland Lore (Loral)", group: "knowledge"},
    {label: "Homeland Lore (Lunar Heartlands)", group: "knowledge"},
    {label: "Homeland Lore (Other)", group: "knowledge"},
    {label: "Homeland Lore (Own)", group: "knowledge"},
    {label: "Homeland Lore (Prax)", group: "knowledge"},
    {label: "Homeland Lore (Sartar)", group: "knowledge"},
    {label: "Homeland Lore (Tarsh)", group: "knowledge"},
    {label: "Homeland Lore (Teleos)", group: "knowledge"},
    {label: "Homeland Lore (Teshnos)", group: "knowledge"},
    {label: "Homeland Lore (Wenelia)", group: "knowledge"},
    {label: "Library Use", group: "knowledge"},
    {label: "Manage Household", group: "knowledge"},
    {label: "Martial Arts (Combat)", group: "knowledge"},
    {label: "Martial Arts ", group: "knowledge"},
    {label: "Mineral lore", group: "knowledge"},
    {label: "Mostali Lore", group: "knowledge"},
    {label: "Peaceful Cut", group: "knowledge"},
    {label: "Plant Lore", group: "knowledge"},
    {label: "Read Write (Auld Wyrmish)", group: "knowledge"},
    {label: "Read Write (Dara Happan)", group: "knowledge"},
    {label: "Read Write (Firespeech)", group: "knowledge"},
    {label: "Read Write (Other)", group: "knowledge"},
    {label: "Read Write (Parlothadi)", group: "knowledge"},
    {label: "Read Write (New Pelorian)", group: "knowledge"},
    {label: "Read Write (Mostali)", group: "knowledge"},
    {label: "ReadWrite Theyalan", group: "knowledge"},
    {label: "River Lore", group: "knowledge"},
    {label: "Sea Lore", group: "knowledge"},
    {label: "Shiphandling", group: "knowledge"},
    {label: "Survival", group: "knowledge"},
    {label: "Treat Disease", group: "knowledge"},
    {label: "Treat Poison", group: "knowledge"},
    {label: "Underworld Lore", group: "knowledge"},
    {label: "Uz Lore", group: "knowledge"},
    {label: "Logician", group: "magic"},
    {label: "Combine (Sorcery Technique)", group: "magic"},
    {label: "Create Image (spell)", group: "magic"},
    {label: "Create Wall of Flames (spell)", group: "magic"},
    {label: "Dissappear (spell)", group: "magic"},
    {label: "Fire (Sorcery Rune)", group: "magic"},
    {label: "Meditate", group: "magic"},
    {label: "Open Seas (spell)", group: "magic"},
    {label: "Prepare Corpse", group: "magic"},
    {label: "Reveal Rune", group: "magic"},
    {label: "Sense Assasin", group: "magic"},
    {label: "Sense Chaos", group: "magic"},
    {label: "Solace of the Logical Mind", group: "magic"},
    {label: "Sorcery Command Technique", group: "magic"},
    {label: "Sorcery Truth Rune Technique", group: "magic"},
    {label: "Speak to Mind Spell", group: "magic"},
    {label: "Spirit Combat", group: "magic"},
    {label: "Spirit Dance", group: "magic"},
    {label: "Spirit Lore", group: "magic"},
    {label: "Spirit Travel", group: "magic"},
    {label: "Total Recall", group: "magic"},
    {label: "Understand Herd Beast", group: "magic"},
    {label: "Worship (Ancestors)", group: "magic"},
    {label: "Worship (Babeester Gor)", group: "magic"},
    {label: "Worship (Donandar)", group: "magic"},
    {label: "Worship (Dormal)", group: "magic"},
    {label: "Worship (Engizi)", group: "magic"},
    {label: "Worship (Ernalda)", group: "magic"},
    {label: "Worship (Eurmal)", group: "magic"},
    {label: "Worship (Humakt)", group: "magic"},
    {label: "Worship (Issaries)", group: "magic"},
    {label: "Worship (Kolat)", group: "magic"},
    {label: "Worship (Lanbril)", group: "magic"},
    {label: "Worship (Lhankor Mhy)", group: "magic"},
    {label: "Worship (Lokarnos)", group: "magic"},
    {label: "Worship (Lumavoxoran)", group: "magic"},
    {label: "Worship (Maran Gor)", group: "magic"},
    {label: "Worship (Odayla)", group: "magic"},
    {label: "Worship (Orlanth)", group: "magic"},
    {label: "Worship (Other)", group: "magic"},
    {label: "Worship (Own)", group: "magic"},
    {label: "Worship (Sartar City Gods)", group: "magic"},
    {label: "Worship (Seven Mothers)", group: "magic"},
    {label: "Worship (Telmor)", group: "magic"},
    {label: "Worship (Yelm)", group: "magic"},
    {label: "Worship (Yelmalio)", group: "magic"},
    {label: "Worship (Ygg)", group: "magic"},
    {label: "Worship (Yinkin)", group: "magic"},
    {label: "Worship (Zola Fel)", group: "magic"},
    {label: "Worship (Chalana Arroy)", group: "magic"},
    {label: "Worship (Storm Bull)", group: "magic"},
    {label: "Conceal", group: "manipulation"},
    {label: "Craft Dwarven Mechanics", group: "manipulation"},
    {label: "Craft (Primary)", group: "manipulation"},
    {label: "Craft (Secondary)", group: "manipulation"},
    {label: "Craft Bowmaking", group: "manipulation"},
    {label: "Craft Carpentry", group: "manipulation"},
    {label: "Craft Ironsmith", group: "manipulation"},
    {label: "Craft Leatherworking", group: "manipulation"},
    {label: "Craft Masonry", group: "manipulation"},
    {label: "Craft Pottery", group: "manipulation"},
    {label: "Craft Redsmithing", group: "manipulation"},
    {label: "Craft Shipbuilding", group: "manipulation"},
    {label: "Craft Swordsmith", group: "manipulation"},
    {label: "Craft Weaving", group: "manipulation"},
    {label: "Craft Cooking", group: "manipulation"},
    {label: "Craft Brewing", group: "manipulation"},
    {label: "Craft Vinification", group: "manipulation"},
    {label: "Craft Jewelry", group: "manipulation"},
    {label: "Craft Fishing", group: "manipulation"},
    {label: "Play Instument (Percussion)", group: "manipulation"},
    {label: "Play Instrument (String)", group: "manipulation"},
    {label: "Play Instrument (Woodwind)", group: "manipulation"},
    {label: "Play Instrument (Primary)", group: "manipulation"},
    {label: "Play Instrument (Seconday)", group: "manipulation"},
    {label: "Devise", group: "manipulation"},
    {label: "Fishing", group: "manipulation"},
    {label: "Foil Restraints", group: "manipulation"},
    {label: "Sleight", group: "manipulation"},
    {label: "Insight (Own Species)", group: "perception"},
    {label: "Insight (Durulz)", group: "perception"},
    {label: "Insight (Human)", group: "perception"},
    {label: "Insight (Minotaur)", group: "perception"},
    {label: "Insight (Other)", group: "perception"},
    {label: "Listen", group: "perception"},
    {label: "Scan", group: "perception"},
    {label: "Scent", group: "perception"},
    {label: "Search", group: "perception"},
    {label: "Streetwise", group: "perception"},
    {label: "Track", group: "perception"},
    {label: "Hide", group: "stealth"},
    {label: "Move Quietly", group: "stealth"},
    {label: "Shadowing", group: "stealth"},
    {label: "Courage", group: "passion"},
    {label: "Cowardly", group: "passion"},
    {label: "Honor", group: "passion"},
    {label: "Devotion (Chalana Arroy)", group: "passion"},
    {label: "Devotion (Engizi)", group: "passion"},
    {label: "Devotion (Ernalda)", group: "passion"},
    {label: "Devotion (Humakt)", group: "passion"},
    {label: "Devotion (Issaries)", group: "passion"},
    {label: "Devotion (Lanbril)", group: "passion"},
    {label: "Devotion (Lhankor Mhy)", group: "passion"},
    {label: "Devotion (Maran Gor)", group: "passion"},
    {label: "Devotion (Orlanth)", group: "passion"},
    {label: "Devotion (Odayla)", group: "passion"},
    {label: "Devotion (Storm Bull)", group: "passion"},
    {label: "Devotion (Yelm)", group: "passion"},
    {label: "Devotion (Yelmalio)", group: "passion"},
    {label: "Devotion (Ygg)", group: "passion"},
    {label: "Devotion (Yinkin)", group: "passion"},
    {label: "Devotion (Zola Fel)", group: "passion"},
    {label: "Devotion (Lumavoxoran)", group: "passion"},
    {label: "Devotion Lokarnos", group: "passion"},
    {label: "Love (Person)", group: "passion"},
    {label: "Love Companion Wolf", group: "passion"},
    {label: "Love Desangian", group: "passion"},
    {label: "Love Diovena", group: "passion"},
    {label: "Love Barfin", group: "passion"},
    {label: "Love Esrala", group: "passion"},
    {label: "Love Elsa", group: "passion"},
    {label: "Love Eriana", group: "passion"},
    {label: "Love Erin Cloud-Hair", group: "passion"},
    {label: "Love Ernalsulva", group: "passion"},
    {label: "Love Family", group: "passion"},
    {label: "Love Farnantyr", group: "passion"},
    {label: "Love Sihala", group: "passion"},
    {label: "Love Harel", group: "passion"},
    {label: "Love Doryn", group: "passion"},
    {label: "Love Jezra", group: "passion"},
    {label: "Love Hazia", group: "passion"},
    {label: "Love Jenvale", group: "passion"},
    {label: "Love Jorjera Latish", group: "passion"},
    {label: "Love Kallinna", group: "passion"},
    {label: "Love Kallyr", group: "passion"},
    {label: "Love Lathwyn", group: "passion"},
    {label: "Love Merripen", group: "passion"},
    {label: "Love Seeker", group: "passion"},
    {label: "Love Vele", group: "passion"},
    {label: "Love Wandle", group: "passion"},
    {label: "Fear Spiders", group: "passion"},
    {label: "Fear Bats", group: "passion"},
    {label: "Fear Giants", group: "passion"},
    {label: "Fear Harrek", group: "passion"},
    {label: "Fear Sea Monsters", group: "passion"},
    {label: "Fear (Primary)", group: "passion"},
    {label: "Fear (Secondary)", group: "passion"},
    {label: "Fear Delecti The Necromancer", group: "passion"},
    {label: "Fear Dragons", group: "passion"},
    {label: "Fear Ghosts", group: "passion"},
    {label: "Fear Rock Lizards", group: "passion"},
    {label: "Fear Wandle", group: "passion"},
    {label: "Hate Mostali", group: "passion"},
    {label: "Hate Beast Folk", group: "passion"},
    {label: "Hate Centaurs", group: "passion"},
    {label: "Hate Busida Moon-Swords", group: "passion"},
    {label: "Hate Yolanva Saedrius", group: "passion"},
    {label: "Hate Darsten Black-Oak", group: "passion"},
    {label: "Hate Sambari Tribe", group: "passion"},
    {label: "Hate (Other)", group: "passion"},
    {label: "Hate (Primary)", group: "passion"},
    {label: "Hate (Secondary)", group: "passion"},
    {label: "Hate Authority", group: "passion"},
    {label: "Hate Cats", group: "passion"},
    {label: "Hate Chaos", group: "passion"},
    {label: "Hate Culbrea", group: "passion"},
    {label: "Hate Dinacoli", group: "passion"},
    {label: "Hate Dogs", group: "passion"},
    {label: "Hate Durulz", group: "passion"},
    {label: "Hate Estal Donge", group: "passion"},
    {label: "Hate Giants", group: "passion"},
    {label: "Hate High Places", group: "passion"},
    {label: "Hate Killer Branduan", group: "passion"},
    {label: "Hate Korlmhyor", group: "passion"},
    {label: "Hate Lismelder", group: "passion"},
    {label: "Hate Lunar Empire", group: "passion"},
    {label: "Hate Ogres", group: "passion"},
    {label: "Hate Phargentes GrinningScar", group: "passion"},
    {label: "Hate Pinfeather", group: "passion"},
    {label: "Hate Praxians", group: "passion"},
    {label: "Hate Telmori", group: "passion"},
    {label: "Hate Trolls", group: "passion"},
    {label: "Hate Tusk Riders", group: "passion"},
    {label: "Hate Undead", group: "passion"},
    {label: "Hate Wolf Pirates", group: "passion"},
    {label: "Loyalty Third Wind", group: "passion"},
    {label: "Loyalty Harrek", group: "passion"},
    {label: "Loyalty Ironhoof", group: "passion"},
    {label: "Loyalty Wild Temple", group: "passion"},
    {label: "Loyalty Yelm Temple of Haragala", group: "passion"},
    {label: "Loyalty Trader Prince Jadulilo", group: "passion"},
    {label: "Loyalty Wolf Pirates", group: "passion"},
    {label: "Loyalty Company of the Dragon", group: "passion"},
    {label: "Loyalty Darna Longcoat", group: "passion"},
    {label: "Loyalty Venharl Stormbrow", group: "passion"},
    {label: "Loyalty Kallyr Starbrow", group: "passion"},
    {label: "Loyalty Haraborn Clan", group: "passion"},
    {label: "Loyalty Greydog Clan", group: "passion"},
    {label: "Loyalty Antorling Clan", group: "passion"},
    {label: "Loyalty Alebards Sisterhood", group: "passion"},
    {label: "Loyalty Temple of Own Cult", group: "passion"},
    {label: "Loyalty Fereva Island", group: "passion"},
    {label: "Loyalty Black Swan Crew", group: "passion"},
    {label: "Loyalty (Clan)", group: "passion"},
    {label: "Loyalty (Deity)", group: "passion"},
    {label: "Loyalty (Other)", group: "passion"},
    {label: "Loyalty (Tribe)", group: "passion"},
    {label: "Loyalty Anas Clan", group: "passion"},
    {label: "Loyalty Argrath", group: "passion"},
    {label: "Loyalty Ashart Dusk-Eater", group: "passion"},
    {label: "Loyalty Blueberry Clan", group: "passion"},
    {label: "Loyalty Bozgadan Band", group: "passion"},
    {label: "Loyalty Captain Vele", group: "passion"},
    {label: "Loyalty Carpatis", group: "passion"},
    {label: "Loyalty Cinsina Tribe", group: "passion"},
    {label: "Loyalty Clearwine Earth Temple", group: "passion"},
    {label: "Loyalty Colymar Tribe", group: "passion"},
    {label: "Loyalty Culbrea Tribe", group: "passion"},
    {label: "Loyalty Culbri Clan", group: "passion"},
    {label: "Loyalty Daughters of Mabodh", group: "passion"},
    {label: "Loyalty Duck Cousins", group: "passion"},
    {label: "Loyalty Durulz", group: "passion"},
    {label: "Loyalty Eamaran", group: "passion"},
    {label: "Loyalty Enestara The Red", group: "passion"},
    {label: "Loyalty Entarios The Supporter", group: "passion"},
    {label: "Loyalty Ernaldori Clan", group: "passion"},
    {label: "Loyalty Estal Donge", group: "passion"},
    {label: "Loyalty Frithan Clan", group: "passion"},
    {label: "Loyalty Gold-Gotti", group: "passion"},
    {label: "Loyalty Greenstone Temple", group: "passion"},
    {label: "Loyalty Hole Lords", group: "passion"},
    {label: "Loyalty House Delaeos", group: "passion"},
    {label: "Loyalty House of Sartar", group: "passion"},
    {label: "Loyalty Indrodars Temple", group: "passion"},
    {label: "Loyalty Isidilian", group: "passion"},
    {label: "Loyalty Jonstown City", group: "passion"},
    {label: "Loyalty Jonstown Library", group: "passion"},
    {label: "Loyalty Kolat Shaman Derkrova", group: "passion"},
    {label: "Loyalty Lismelder Tribe", group: "passion"},
    {label: "Loyalty Maboder Tribe", group: "passion"},
    {label: "Loyalty MaEsra Thieves", group: "passion"},
    {label: "Loyalty Malani Tribe", group: "passion"},
    {label: "Loyalty Merripen", group: "passion"},
    {label: "Loyalty Minaryth Purple", group: "passion"},
    {label: "Loyalty Newtlings", group: "passion"},
    {label: "Loyalty Nochet", group: "passion"},
    {label: "Loyalty Orlmarth Clan", group: "passion"},
    {label: "Loyalty Own Group (Wyter)", group: "passion"},
    {label: "Loyalty Own Pact", group: "passion"},
    {label: "Loyalty Patrol Unit", group: "passion"},
    {label: "Loyalty Red Cow Clan", group: "passion"},
    {label: "Loyalty Samastina", group: "passion"},
    {label: "Loyalty Sartar", group: "passion"},
    {label: "Loyalty Shaker Temple", group: "passion"},
    {label: "Loyalty Split Waters Clan", group: "passion"},
    {label: "Loyalty Underwillow Clan", group: "passion"},
    {label: "Loyalty Unit Leader Jaranil", group: "passion"},
    {label: "Loyalty Unit Leader", group: "passion"},
    {label: "Loyalty Yanioth Brandgorsdottir", group: "passion"},
    {label: "Lust Women", group: "passion"},
    {label: "Star Heart", group: "passion"},
    {label: "Air", group: "rune"},
    {label: "Beast", group: "rune"},
    {label: "Chaos", group: "rune"},
    {label: "Darkness", group: "rune"},
    {label: "Death", group: "rune"},
    {label: "Disorder", group: "rune"},
    {label: "Earth", group: "rune"},
    {label: "Fertility", group: "rune"},
    {label: "Fire", group: "rune"},
    {label: "Harmony", group: "rune"},
    {label: "Illumination", group: "rune"},
    {label: "Illusion", group: "rune"},
    {label: "Man", group: "rune"},
    {label: "Moon", group: "rune"},
    {label: "Movement", group: "rune"},
    {label: "Sartar", group: "rune"},
    {label: "Spirit", group: "rune"},
    {label: "Stasis", group: "rune"},
    {label: "Truth", group: "rune"},
    {label: "Water", group: "rune"},
    {label: "Speak Own Language (Tanyen)", group: "communication"},
    {label: "Customs (Haragalan commonwealth)", group: "knowledge"},
    {label: "Homeland Lore (Haragalan Islands)", group: "knowledge"}, 
    {label: "Homeland Lore (Korolan Islands)", group: "knowledge"},
    {label: "Cult Lore (Finzalvo)", group: "knowledge"},
    {label: "Cult Lore (Karkal)", group: "knowledge"},
    {label: "Cult Lore (Irvata)", group: "knowledge"},
    {label: "Cult Lore (Mingemelor)", group: "knowledge"},
    {label: "Worship (Finzalvo)", group: "magic"},
    {label: "Worship (Karkal)", group: "magic"},
    {label: "Worship (Irvata)", group: "magic"},
    {label: "Worship (Mingemelor)", group: "magic"},
    {label: "Cult Lore (Enevar)", group: "knowledge"},
    {label: "Worship (Enevar)", group: "magic"}
]

export const WEAPON_SKILLS = [
    {label: "1h Axe", group: "weapon"},
    {label: "1h Mace", group: "weapon"},
    {label: "2h Mace", group: "weapon"},
    {label: "Maul", group: "weapon"},
    {label: "Great Hammer", group: "weapon"},
    {label: "1h Spear", group: "weapon"},
    {label: "2h Axe", group: "weapon"},
    {label: "2h Spear", group: "weapon"},
    {label: "2h Sword", group: "weapon"},
    {label: "Bite", group: "weapon"},
    {label: "Broadsword", group: "weapon"},
    {label: "Claw", group: "weapon"},
    {label: "Composite Bow", group: "weapon"},
    {label: "Self Bow", group: "weapon"},
    {label: "Crossbow", group: "weapon"},
    {label: "Dagger", group: "weapon"},
    {label: "Fist", group: "weapon"},
    {label: "Grapple", group: "weapon"},
    {label: "Javelin", group: "weapon"},
    {label: "Kick", group: "weapon"},
    {label: "Kopis", group: "weapon"},
    {label: "Lance", group: "weapon"},
    {label: "Pistol", group: "weapon"},
    {label: "Shield Large", group: "weapon"},
    {label: "Shield Medium", group: "weapon"},
    {label: "Shield Small", group: "weapon"},
    {label: "Shortsword", group: "weapon"},
    {label: "Sling", group: "weapon"},
    {label: "Throwing Axe", group: "weapon"},
    {label: "Throwing Dagger", group: "weapon"},
    {label: "Throwing Net", group: "weapon"},
    {label: "Arbalest", group: "weapon"},
    {label: "Ballista", group: "weapon"},
    {label: "Cannon", group: "weapon"},
    {label: "Atlatl", group: "weapon"},
    {label: "Rock Throwing", group: "weapon"},
    {label: "Staff Sling", group: "weapon"},
    {label: "Cestus Light", group: "weapon"},
    {label: "Cestus Heavy", group: "weapon"},
    {label: "Sickle Sword", group: "weapon"},
    {label: "Rhomphaia", group: "weapon"},
    {label: "Rapier", group: "weapon"},
    {label: "Sickle Dagger", group: "weapon"},
    {label: "Small Axe", group: "weapon"},
    {label: "Head Butt", group: "weapon"}
]

export const ARMOR = [
    {label: "Soft leather", value: 1, weight: [3.0, 4.0, 5.0, 6.0]},
    {label: "Bezainted", value: 4, weight: [6.0, 7.5, 9.0, 10.5]},
    {label: "Chainmail", value: 7, weight: [16.0, 20.0, 24.0, 28.0]},
    {label: "Cuirboul", value: 3, weight: [5.0, 6.0, 7.0, 8.0]},
    {label: "Hard leather", value: 2, weight: [4.0, 5.0, 6.0, 7.0]},
    {label: "Lamellar", value: 6, weight: [14.0, 18.0, 21.5, 25.0]},
    {label: "Plate", value: 8, weight: [20.0, 25.0, 30.0, 35.0]},
    {label: "Ringmail", value: 5, weight: [8.0, 10.0, 12.0, 14.0]},
    {label: "Steel Bezainted", value: 6, weight: [6.0, 7.5, 9.0, 10.5]},
    {label: "Steel Lamellar", value: 9, weight: [14.0, 18.0, 21.5, 25.0]},
    {label: "Steel Plate", value: 12, weight: [20.0, 25.0, 30.0, 35.0]},
    {label: "Steel Ringmail", value: 7, weight: [8.0, 10.0, 12.0, 14.0]}
]