export const SKILLS = [
  { label: "Boat", group: "dexterity" },
  { label: "Climb", group: "dexterity" },
  { label: "Dodge", group: "dexterity" },
  { label: "Jump", group: "dexterity" },
  { label: "Ride", group: "dexterity" },
  { label: "Swim", group: "dexterity" },
  { label: "Throw", group: "dexterity" },
  { label: "Fast talk", group: "communication" },
  { label: "Orate", group: "communication" },
  { label: "Sing", group: "communication" },
  { label: "Speak Language: Own", group: "communication" },
  { label: "Animal lore", group: "knowledge" },
  { label: "Craft", group: "knowledge" },
  { label: "Evaluate", group: "knowledge" },
  { label: "First aid", group: "knowledge" },
  { label: "Human lore", group: "knowledge" },
  { label: "Martial arts", group: "knowledge" },
  { label: "Mineral lore", group: "knowledge" },
  { label: "Plant Lore", group: "knowledge" },
  { label: "Shiphandling", group: "knowledge" },
  { label: "World Lore", group: "knowledge" },
  { label: "Conceal", group: "manipulation" },
  { label: "Devise", group: "manipulation" },
  { label: "Sleight", group: "manipulation" },
  { label: "Listen", group: "perception" },
  { label: "Scan", group: "perception" },
  { label: "Search", group: "perception" },
  { label: "Track", group: "perception" },
  { label: "Hide", group: "stealth" },
  { label: "Sneak", group: "stealth" },
  { label: "Ceremony", group: "magic" },
  { label: "Enchant", group: "magic" },
  { label: "Summon", group: "magic" },
  { label: "Duration", group: "magic" },
  { label: "Intensity", group: "magic" },
  { label: "Multispell", group: "magic" },
  { label: "Range", group: "magic" },
  { label: "Dance (Spirit Dance)", group: "dexterity" },
  { label: "ReadWrite Old Pavic", group: "knowledge" },
  { label: "ReadWrite Praxian Knotmarks", group: "knowledge" },
  { label: "ReadWrite New Pelorian", group: "knowledge" },
  { label: "ReadWrite Sartarite", group: "knowledge" },
  { label: "ReadWrite Tarshite", group: "knowledge" },
  { label: "ReadWrite Boatspeech", group: "knowledge" },
  { label: "ReadWrite Firespeech", group: "knowledge" },
  { label: "ReadWrite Spiritspeech", group: "knowledge" },
  { label: "ReadWrite Dark Tongue", group: "knowledge" },
  { label: "ReadWrite Malkioni", group: "knowledge" },
  { label: "ReadWrite Tradetalk", group: "knowledge" },
  { label: "ReadWrite Earth Tongue", group: "knowledge" },
  { label: "ReadWrite Mostali", group: "knowledge" },
  { label: "ReadWrite Stormspeech", group: "knowledge" },
  { label: "Alchemical Lore", group: "knowledge" },
  { label: "Chaos Lore", group: "knowledge" },
  { label: "Dwarf Lore", group: "knowledge" },
  { label: "Demon Lore", group: "knowledge" },
  { label: "HeroPlane Lore", group: "knowledge" },
  { label: "Poison Lore", group: "knowledge" },
  { label: "Spirit Lore", group: "knowledge" },
  { label: "Duck Lore", group: "knowledge" },
  { label: "Refine Medicine", group: "knowledge" },
  { label: "Peaceful Cut", group: "knowledge" },
  { label: "Butchering", group: "knowledge" },
  { label: "Find Water", group: "knowledge" },
  { label: "Swordsmithing", group: "knowledge" },
  { label: "Axesmithing", group: "knowledge" },
  { label: "Ironsmith", group: "knowledge" },
  { label: "Treat Disease", group: "knowledge" },
  { label: "Treat Poison", group: "knowledge" },
  { label: "Courtesan", group: "knowledge" },
  { label: "(Own) Cult Lore", group: "knowledge" },
  { label: "Streetwise", group: "knowledge" },
  { label: "Map Making", group: "knowledge" },
  { label: "Prepare Corpse", group: "knowledge" },
  { label: "Disguise", group: "knowledge" },{ label: "Speak Old Pavic", group: "communication" },
  { label: "Speak Praxian", group: "communication" },
  { label: "Speak New Pelorian", group: "communication" },
  { label: "Speak Sartarite", group: "communication" },
  { label: "Speak Tarshite", group: "communication" },
  { label: "Speak Boatspeech", group: "communication" },
  { label: "Speak Firespeech", group: "communication" },
  { label: "Speak Spiritspeech", group: "communication" },
  { label: "Speak Dark Tongue", group: "communication" },
  { label: "Speak Malkioni", group: "communication" },
  { label: "Speak Tradetalk", group: "communication" },
  { label: "Speak Earth Tongue", group: "communication" },
  { label: "Speak Beast Talk", group: "communication" },
  { label: "Speak Mostali", group: "communication" },
  { label: "Speak Thief´s Argot", group: "communication" },
  { label: "Speak Horn Gate", group: "communication" },
  { label: "Speak Stormspeech", group: "communication" },
  { label: "Play Drum", group: "manipulation" },
  { label: "Play Flute", group: "manipulation" },
  { label: "Arts Painting", group: "manipulation" },
  { label: "Drive Vehicle", group: "manipulation" },
  { label: "Spirit Travel", group: "magic" },
  { label: "Alchemy Skills (varies)", group: "magic" },
  { label: "Sense Chaos", group: "perception" },
  { label: "Understand Herd Beast", group: "perception" },
  { label: "Sense Assassin", group: "perception" },
  { label: "Palsy ", group: "magic" },
  { label: "Stupefaction ", group: "magic" }, 
  { label: "Tap POW ", group: "magic" },
  { label: "Mystic Vision ", group: "magic" }, 
  { label: "Spell Matrix Enchantment ", group: "magic" },
  { label: "Boost Damage ", group: "magic" }, 
  { label: "Resist Spirit ", group: "magic" },
  { label: "Apprentice Bonding ", group: "magic" }, 
  { label: "Haste ", group: "magic" },
  { label: "Animate Stone", group: "magic" }, 
  { label: "FormSet Stone", group: "magic" },
  { label: "Glow ", group: "magic" }, 
  { label: "Smother ", group: "magic" },
  { label: "Project (Sense) ", group: "magic" }, 
  { label: "Resist Spell ", group: "magic" },
  { label: "Resist Damage ", group: "magic" }, 
  { label: "Telepathy ", group: "magic" },
  { label: "Enhance STR", group: "magic" }, 
  { label: "Enhance CON", group: "magic" },
  { label: "Enhance SIZ", group: "magic" }, 
  { label: "Enhance DEX", group: "magic" },
  { label: "Neutralize Magic ", group: "magic" },
  { label: "Undead Lore", group: "knowledge" }, 
  { label: "Swamp Lore", group: "knowledge" }, 
  { label: "Magic Lore", group: "knowledge" } 
]

export const WEAPON_SKILLS = [
  { label: "Axe 1h", group: "weapon" },
  { label: "Axe 2h", group: "weapon" },
  { label: "Dagger", group: "weapon" },
  { label: "Fist", group: "weapon" },
  { label: "Kick", group: "weapon" },
  { label: "Flail 1h", group: "weapon" },
  { label: "Flail 2h", group: "weapon" },
  { label: "Hammer 1h", group: "weapon" },
  { label: "Hammer 2h", group: "weapon" },
  { label: "Mace 1h", group: "weapon" },
  { label: "Maul 2h", group: "weapon" },
  { label: "Rapier", group: "weapon" },
  { label: "Shortsword", group: "weapon" },
  { label: "Shield", group: "weapon" },
  { label: "Spear 1h", group: "weapon" },
  { label: "Spear 2h", group: "weapon" },
  { label: "Sword 1h", group: "weapon" },
  { label: "Sword 2h", group: "weapon" }, 
  { label: "Tools", group: "weapon" },
  { label: "Atlatl", group: "weapon" },
  { label: "Bola", group: "weapon" },
  { label: "Crossbow", group: "weapon" },
  { label: "Stonebow", group: "weapon" },
  { label: "Bow", group: "weapon" },
  { label: "Thrown Weapon", group: "weapon" },
  { label: "Lasso and Whip", group: "weapon" },
  { label: "Sling", group: "weapon" },
  { label: "Blowgun", group: "weapon" },
  { label: "Shuriken", group: "weapon" },
  { label: "Dart", group: "weapon" },
  { label: "Projectile Spell", group: "weapon" }
]

export const ARMOR = [
  { label: "Soft leather", value: 1 , weight: [3.0, 4.0, 5.0, 6.0] },
  { label: "Hard leather", value: 2 , weight: [4.0, 5.0, 6.0, 7.0] },
  { label: "Cuirboul", value: 3, weight:[5.0, 6.0, 7.0, 8.0] }, 
  { label: "Bezainted", value: 4, weight:[6.0, 7.5, 9.0, 10.5] },
  { label: "Ringmail", value: 5 , weight: [8.0, 10.0, 12.0, 14.0] },
  { label: "Lamellar", value: 6 , weight: [14.0, 18.0, 21.5, 25.0] },
  { label: "Steel Bezainted", value: 6, weight:[6.0, 7.5, 9.0, 10.5] },
  { label: "Steel Ringmail", value: 7 , weight: [8.0, 10.0, 12.0, 14.0] },
  { label: "Chainmail", value: 7 , weight: [16.0, 20.0, 24.0, 28.0] },
  { label: "Plate", value: 8, weight:[20.0, 25.0, 30.0, 35.0] },
  { label: "Steel Lamellar", value: 9 , weight: [14.0, 18.0, 21.5, 25.0] },
  { label: "Steel Plate", value: 12, weight:[20.0, 25.0, 30.0, 35.0] }
]