export const SKILLS = [
  { label: "Boat", group: "dexterity" },
  { label: "Climb", group: "dexterity" },
  { label: "Dodge", group: "dexterity" },
  { label: "Drive", group: "dexterity" },
  { label: "Jump", group: "dexterity" },
  { label: "Ride", group: "dexterity" },
  { label: "Swim", group: "dexterity" },
  { label: "Act", group: "communication" },
  { label: "Art", group: "communication" },
  { label: "Bargain", group: "communication" },
  { label: "Charm", group: "communication" },
  { label: "Dance", group: "communication" },
  { label: "Disguise", group: "communication" },
  { label: "Fast talk", group: "communication" },
  { label: "Intimidate", group: "communication" },
  { label: "Intrigue", group: "communication" },
  { label: "Orate", group: "communication" },
  { label: "Sing", group: "communication" },
  { label: "Speak Heortling", group: "communication" },
  { label: "Speak Tradetalk", group: "communication" },
  { label: "Speak Earth Tongue", group: "communication" },
  { label: "Speak Beast Speech", group: "communication" },
  { label: "Speak Stormspeech", group: "communication" },
  { label: "Speak (Other)", group: "communication" },
  { label: "Alchemy", group: "knowledge" },
  { label: "Animal lore", group: "knowledge" },
  { label: "Battle", group: "knowledge" },
  { label: "Bureaucracy", group: "knowledge" },
  { label: "Celestial Lore", group: "knowledge" },
  { label: "Cult Lore (Yinkin)", group: "knowledge" },
  { label: "Cult Lore (Orlanth)", group: "knowledge" },
  { label: "Cult Lore (Ernalda)", group: "knowledge" },
  { label: "Cult Lore (Other)", group: "knowledge" },
  { label: "Customs (Own)", group: "knowledge" },
  { label: "Customs (Other)", group: "knowledge" },
  { label: "Elder Races Lore", group: "knowledge" },
  { label: "Evaluate", group: "knowledge" },
  { label: "Farm", group: "knowledge" },
  { label: "First Aid", group: "knowledge" },
  { label: "Game", group: "knowledge" },
  { label: "Herd", group: "knowledge" },
  { label: "Homeland Lore (Own)", group: "knowledge" },
  { label: "Homeland Lore (Other)", group: "knowledge" },
  { label: "Library Use", group: "knowledge" },
  { label: "Manage Household", group: "knowledge" },
  { label: "Mineral lore", group: "knowledge" },
  { label: "Peaceful Cut", group: "knowledge" },
  { label: "Plant Lore", group: "knowledge" },
  { label: "ReadWrite Heortling", group: "knowledge" },
  { label: "ReadWrite (Other)", group: "knowledge" },
  { label: "Shiphandling", group: "knowledge" },
  { label: "Survival", group: "knowledge" },
  { label: "Treat Disease", group: "knowledge" },
  { label: "Treat Poison", group: "knowledge" },
  { label: "Meditate", group: "magic" },
  { label: "Prepare Corpse", group: "magic" },
  { label: "Sense Assasin", group: "magic" },
  { label: "Sense Chaos", group: "magic" },
  { label: "Spirit Combat", group: "magic" },
  { label: "Spirit Dance", group: "magic" },
  { label: "Spirit Lore", group: "magic" },
  { label: "Spirit Travel", group: "magic" },
  { label: "Understand Herd Beast", group: "magic" },
  { label: "Worship (Own)", group: "magic" },
  { label: "Worship (Other)", group: "magic" },
  { label: "Conceal", group: "manipulation" },
  { label: "Craft (Primary)", group: "manipulation" },
  { label: "Craft (Secondary)", group: "manipulation" },
  { label: "Devise", group: "manipulation" },
  { label: "Play Instrument (Primary)", group: "manipulation" },
  { label: "Play Instrument (Seconday)", group: "manipulation" },
  { label: "Sleight", group: "manipulation" },
  { label: "Insight (Own Species)", group: "perception" },
  { label: "Insight (Other)", group: "perception" },
  { label: "Listen", group: "perception" },
  { label: "Scan", group: "perception" },
  { label: "Search", group: "perception" },
  { label: "Track", group: "perception" },
  { label: "Hide", group: "stealth" },
  { label: "Move Quietly", group: "stealth" },
  { label: "Love Family", group: "passion" },
  { label: "Love (Person)", group: "passion" },
  { label: "Loyalty (Clan)", group: "passion" },
  { label: "Loyalty (Tribe)", group: "passion" },
  { label: "Loyalty (Deity)", group: "passion" },
  { label: "Loyalty (Other)", group: "passion" },
  { label: "Hate (Primary)", group: "passion" },
  { label: "Hate (Secondary)", group: "passion" },
  { label: "Hate (Other)", group: "passion" },
  { label: "Hate (Dinacoli)", group: "passion" },
  { label: "Hate (Telmori)", group: "passion" },
  { label: "Courage", group: "passion" },
  { label: "Star Heart", group: "passion" },
  { label: "Fear (Primary)", group: "passion" },
  { label: "Fear (Secondary)", group: "passion" },
  { label: "Air", group: "rune" },
  { label: "Fire", group: "rune" },
  { label: "Darkness", group: "rune" },
  { label: "Water", group: "rune" },
  { label: "Earth", group: "rune" },
  { label: "Moon", group: "rune" },
  { label: "Fertility", group: "rune" },
  { label: "Death", group: "rune" },
  { label: "Harmony", group: "rune" },
  { label: "Disorder", group: "rune" },
  { label: "Truth", group: "rune" },
  { label: "Illusion", group: "rune" },
  { label: "Stasis", group: "rune" },
  { label: "Movement", group: "rune" },
  { label: "Man", group: "rune" },
  { label: "Beast", group: "rune" },
  { label: "Speak River Speech", group: "communication" },
  { label: "Honor", group: "passion" },
  { label: "Fly", group: "dexterity" }
]

export const WEAPON_SKILLS = [
  { label: "1h Axe", group: "weapon" },
  { label: "2h Axe", group: "weapon" },
  { label: "Broadsword", group: "weapon" },
  { label: "Dagger", group: "weapon" },
  { label: "1h Mace", group: "weapon" },
  { label: "Shortsword", group: "weapon" },
  { label: "1h Spear", group: "weapon" },
  { label: "2h Spear", group: "weapon" },
  { label: "Composite Bow", group: "weapon" },
  { label: "Javelin", group: "weapon" },
  { label: "Sling", group: "weapon" },
  { label: "Throwing Dagger", group: "weapon" },
  { label: "Throwing Axe", group: "weapon" },
  { label: "Shield Small", group: "weapon" },
  { label: "Shield Medium", group: "weapon" },
  { label: "Shield Large", group: "weapon" },
  { label: "Fist", group: "weapon" },
  { label: "Grapple", group: "weapon" },
  { label: "Kick", group: "weapon" }
]

export const ARMOR = [
  { label: "Soft leather", value: 1 , weight: [3.0, 4.0, 5.0, 6.0] },
  { label: "Hard leather", value: 2 , weight: [4.0, 5.0, 6.0, 7.0] },
  { label: "Cuirboul", value: 3, weight:[5.0, 6.0, 7.0, 8.0] }, 
  { label: "Bezainted", value: 4, weight:[6.0, 7.5, 9.0, 10.5] },
  { label: "Ringmail", value: 5 , weight: [8.0, 10.0, 12.0, 14.0] },
  { label: "Lamellar", value: 6 , weight: [14.0, 18.0, 21.5, 25.0] },
  { label: "Steel Bezainted", value: 6, weight:[6.0, 7.5, 9.0, 10.5] },
  { label: "Steel Ringmail", value: 7 , weight: [8.0, 10.0, 12.0, 14.0] },
  { label: "Chainmail", value: 7 , weight: [16.0, 20.0, 24.0, 28.0] },
  { label: "Plate", value: 8, weight:[20.0, 25.0, 30.0, 35.0] },
  { label: "Steel Lamellar", value: 9 , weight: [14.0, 18.0, 21.5, 25.0] },
  { label: "Steel Plate", value: 12, weight:[20.0, 25.0, 30.0, 35.0] }
]